### ISSUE TITLE
support hydra hosted on some pathname

### ISSUE THREAD

**Issue by dastein1** [Exact-Realty/ts-hydra-rfc8693#11]
I noticed that when the hydra is hosted on some path (e.g. https://my.domain.org/ws/hydra) the concatenation logic in step 3 and 5 may not work. 
The authorization flow starts with `${hydraPublicUri}/oauth2/auth` so `hydraPublicUri` must be set to https://my.domain.org/ws/hydra. In step 3 and 5 then the _pathname_ and _search_ of the _redirect_to_ are appended to the _hydraPublicUri_. However this may then lead to having parts of that pathnames duplicated.

Is there a particular reason why those requests can't simply be made against _consentDestination_ or the _finalDestination_?

**Comment by corrideat** [comment]
Hi @dastein1,

Thanks for reporting this issue. Hosting Hydra on a path wasn't (fully) considered because it breaks some of the public API (especially the `/.well-known` endpoints).

However, we can look into this. The main argument against making the request to the returned path is that the data can be potentially untrusted and leak information, although I'm thinking that this scenario is probably difficult to exploit.

I see two solutions to this. One of them is using the returned values, the other one is handling the duplicate paths. I'll be making a new release using one of these approaches.

**Comment by corrideat** [comment]
This should work now in v1.1.5.
